### ISSUE TITLE
Empty galaxy issue

### ISSUE THREAD

**Issue by StellarisEnjoyer** [Nro001/Nro-Galaxy-Editor#2] opened 2022-08-14 16:06 UTC
so ive just used the galaxy editor and everything went smoothly, i loaded up the save and the changes were there but i was in a weird pseudo-observer mode that when i click on any star it just takes me to an empty space like a solar system but it doesnt have anything, the hyperlanes to other systems are there but aside from that its just empty

i tried using the play 00 command and observer command but nothing works so all i have left is a perfectly made empty fortress galaxy. any help would be appreciated!

**Comment by Nro001** [comment] 2022-08-14 19:51
Have you tried following the steps on a [similar issue](https://github.com/Nro001/Nro-Galaxy-Editor/issues/1)? 

If none of them works, please let me know and send me your save-file.

**Comment by jcz18** [comment] 2022-08-17 01:34
Hey, had the same issue as this, I think the issue is starbase_mgr ends up being removed somehow in the gamestate file, doing the galactic_object={ method works fine though. To be clear though, it's not related to the other issue that was closed, what he means is that the save will load fine without any errors and all the stars exist but there will be no fog of war, empires, etc. Attached my save file as a txt (remove the extension) and the output files.
[galactic_object-modified.txt](https://github.com/Nro001/Nro-Galaxy-Editor/files/9355626/galactic_object-modified.txt)
[ironman.sav.txt](https://github.com/Nro001/Nro-Galaxy-Editor/files/9355623/ironman.sav.txt)
[gamestate.txt](https://github.com/Nro001/Nro-Galaxy-Editor/files/9355625/gamestate.txt)

**Comment by Nro001** [comment] 2022-08-19 16:44
Ah, I see. The gamestate method is usually buggy, it works well on early-game saves than mid to late-game saves, either way, I'd advice to use `galactic_object={` method.

On the new version, I have now fixed the issue of `starbase_mgr` being removed from the gamestate file, hopefully it fixes that issue.

**Closed by Nro001** 2022-08-19 16:44 UTC
